# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  amd-ctk = {
    pname = "amd-ctk";
    version = "v1.3.0";
    src = fetchFromGitHub {
      owner = "ROCm";
      repo = "container-toolkit";
      rev = "v1.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-+YqVm/u0PYvyoHUSwRapByvmIunZUfcPV5rYDFW7Ifs=";
    };
    extract = {
      "go.mod" = ./. + "/sha256-+YqVm_u0PYvyoHUSwRapByvmIunZUfcPV5rYDFW7Ifs=/go.mod";
      "go.sum" = ./. + "/sha256-+YqVm_u0PYvyoHUSwRapByvmIunZUfcPV5rYDFW7Ifs=/go.sum";
    };
  };
  cq = {
    pname = "cq";
    version = "cli/v0.16.0";
    src = fetchFromGitHub {
      owner = "mozilla-ai";
      repo = "cq";
      rev = "cli/v0.16.0";
      fetchSubmodules = false;
      sha256 = "sha256-kyr/vUSIstrQ8HQJ3nbol2LOg6qnBdDUPc5RhKj5SOQ=";
    };
    extract = {
      "cli/go.sum" = ./. + "/sha256-kyr_vUSIstrQ8HQJ3nbol2LOg6qnBdDUPc5RhKj5SOQ=/cli/go.sum";
      "cli/go.mod" = ./. + "/sha256-kyr_vUSIstrQ8HQJ3nbol2LOg6qnBdDUPc5RhKj5SOQ=/cli/go.mod";
    };
  };
  graphrag = {
    pname = "graphrag";
    version = "v3.1.1";
    src = fetchFromGitHub {
      owner = "microsoft";
      repo = "graphrag";
      rev = "v3.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-BW9czN4+ZDp/5CBfEYX/SKDgJH+BQZtFTALwnNXl5G0=";
    };
  };
  llm-wiki-compiler = {
    pname = "llm-wiki-compiler";
    version = "v1.1.0";
    src = fetchFromGitHub {
      owner = "atomicstrata";
      repo = "llm-wiki-compiler";
      rev = "v1.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-ANlXSxnyAkVdPiwrdDA+clAiAPY1jXfVhnPdZYZc84Q=";
    };
    extract = {
      "package-lock.json" = ./. + "/sha256-ANlXSxnyAkVdPiwrdDA+clAiAPY1jXfVhnPdZYZc84Q=/package-lock.json";
    };
  };
  open-code-review = {
    pname = "open-code-review";
    version = "v1.7.16";
    src = fetchFromGitHub {
      owner = "alibaba";
      repo = "open-code-review";
      rev = "v1.7.16";
      fetchSubmodules = false;
      sha256 = "sha256-ZzcPbXnK/axRVnh0USC0nQgXx+3GGU7Z17jWrhg3Wfs=";
    };
    extract = {
      "go.mod" = ./. + "/sha256-ZzcPbXnK_axRVnh0USC0nQgXx+3GGU7Z17jWrhg3Wfs=/go.mod";
      "go.sum" = ./. + "/sha256-ZzcPbXnK_axRVnh0USC0nQgXx+3GGU7Z17jWrhg3Wfs=/go.sum";
    };
  };
  openkb = {
    pname = "openkb";
    version = "v0.4.5";
    src = fetchFromGitHub {
      owner = "vectifyai";
      repo = "openkb";
      rev = "v0.4.5";
      fetchSubmodules = false;
      sha256 = "sha256-vEYlcFe4vFVUpZIcVUbaZhmsSDDrNXFjKJpKb+/fqBQ=";
    };
  };
}
