# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  amd-ctk = {
    pname = "amd-ctk";
    version = "v1.3.0";
    src = fetchFromGitHub {
      owner = "ROCm";
      repo = "container-toolkit";
      rev = "v1.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-+YqVm/u0PYvyoHUSwRapByvmIunZUfcPV5rYDFW7Ifs=";
    };
    extract = {
      "go.mod" = ./. + "/sha256-+YqVm_u0PYvyoHUSwRapByvmIunZUfcPV5rYDFW7Ifs=/go.mod";
      "go.sum" = ./. + "/sha256-+YqVm_u0PYvyoHUSwRapByvmIunZUfcPV5rYDFW7Ifs=/go.sum";
    };
  };
}
