# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  amd-ctk = {
    pname = "amd-ctk";
    version = "v1.3.0";
    src = fetchFromGitHub {
      owner = "ROCm";
      repo = "container-toolkit";
      rev = "v1.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-+YqVm/u0PYvyoHUSwRapByvmIunZUfcPV5rYDFW7Ifs=";
    };
    extract = {
      "go.mod" = ./. + "/sha256-+YqVm_u0PYvyoHUSwRapByvmIunZUfcPV5rYDFW7Ifs=/go.mod";
      "go.sum" = ./. + "/sha256-+YqVm_u0PYvyoHUSwRapByvmIunZUfcPV5rYDFW7Ifs=/go.sum";
    };
  };
  cq = {
    pname = "cq";
    version = "cli/v0.17.0";
    src = fetchFromGitHub {
      owner = "mozilla-ai";
      repo = "cq";
      rev = "cli/v0.17.0";
      fetchSubmodules = false;
      sha256 = "sha256-tYDq8BcI/6klLDZbhMtkGQeUs9HYpfGSor2ZCf5iAGo=";
    };
    extract = {
      "cli/go.sum" = ./. + "/sha256-tYDq8BcI_6klLDZbhMtkGQeUs9HYpfGSor2ZCf5iAGo=/cli/go.sum";
      "cli/go.mod" = ./. + "/sha256-tYDq8BcI_6klLDZbhMtkGQeUs9HYpfGSor2ZCf5iAGo=/cli/go.mod";
    };
  };
  graphrag = {
    pname = "graphrag";
    version = "v3.1.1";
    src = fetchFromGitHub {
      owner = "microsoft";
      repo = "graphrag";
      rev = "v3.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-BW9czN4+ZDp/5CBfEYX/SKDgJH+BQZtFTALwnNXl5G0=";
    };
  };
  llama-swap = {
    pname = "llama-swap";
    version = "b40d20e91660a0c6c0d3369aab410b42f591f1d2";
    src = fetchgit {
      url = "https://github.com/chaserhkj/llama-swap";
      rev = "b40d20e91660a0c6c0d3369aab410b42f591f1d2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-5ra0QXIgmdYMZHRNVg0uivvgpM9Ca4frmH9B7dTo7C4=";
    };
    extract = {
      "ui/package-lock.json" = ./. + "/sha256-5ra0QXIgmdYMZHRNVg0uivvgpM9Ca4frmH9B7dTo7C4=/ui/package-lock.json";
      "go.mod" = ./. + "/sha256-5ra0QXIgmdYMZHRNVg0uivvgpM9Ca4frmH9B7dTo7C4=/go.mod";
      "go.sum" = ./. + "/sha256-5ra0QXIgmdYMZHRNVg0uivvgpM9Ca4frmH9B7dTo7C4=/go.sum";
    };date = "2026-08-18";
  };
  llm-wiki-compiler = {
    pname = "llm-wiki-compiler";
    version = "v1.1.0";
    src = fetchFromGitHub {
      owner = "atomicstrata";
      repo = "llm-wiki-compiler";
      rev = "v1.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-ANlXSxnyAkVdPiwrdDA+clAiAPY1jXfVhnPdZYZc84Q=";
    };
    extract = {
      "package-lock.json" = ./. + "/sha256-ANlXSxnyAkVdPiwrdDA+clAiAPY1jXfVhnPdZYZc84Q=/package-lock.json";
    };
  };
  open-code-review = {
    pname = "open-code-review";
    version = "v1.9.6";
    src = fetchFromGitHub {
      owner = "alibaba";
      repo = "open-code-review";
      rev = "v1.9.6";
      fetchSubmodules = false;
      sha256 = "sha256-wwR0aXOHqwUB6CNSVptczU5/xTFXtLd25HvNmFyZDUY=";
    };
    extract = {
      "go.mod" = ./. + "/sha256-wwR0aXOHqwUB6CNSVptczU5_xTFXtLd25HvNmFyZDUY=/go.mod";
      "go.sum" = ./. + "/sha256-wwR0aXOHqwUB6CNSVptczU5_xTFXtLd25HvNmFyZDUY=/go.sum";
    };
  };
  openkb = {
    pname = "openkb";
    version = "v0.4.5";
    src = fetchFromGitHub {
      owner = "vectifyai";
      repo = "openkb";
      rev = "v0.4.5";
      fetchSubmodules = false;
      sha256 = "sha256-vEYlcFe4vFVUpZIcVUbaZhmsSDDrNXFjKJpKb+/fqBQ=";
    };
  };
}
