# Host-specific configuration stage, adds configuration only
# Assuming we are building from ../arch-base, but this could be overridden
FROM bootc-arch-base as base

# Add additional host-specific packages from build context, if any
RUN --mount=type=bind,target=/tmp/ctx \
    --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    [ -f /tmp/ctx/PKGS ] && { pacman -Sy - --noconfirm --needed </tmp/ctx/PKGS; } || exit 0

# Adding layer
COPY rootfs /

RUN --mount=type=secret,id=creds \
    chpasswd < /run/secrets/creds

RUN --mount=type=secret,id=ncps_cred \
    cp /run/secrets/ncps_cred /etc/nix/ncps.cred.txt && \
    chown hkj:hkj /etc/nix/ncps.cred.txt && chmod 0400 /etc/nix/ncps.cred.txt

# Run setup script from build context, if any
RUN --mount=type=bind,target=/tmp/ctx \
    [ -f /tmp/ctx/setup.sh ] && bash /tmp/ctx/setup.sh || exit 0
