set dotenv-load := true
CTR_ARCH_BOOTC_HOST_TARGET_IMG_REF := env("CTR_ARCH_BOOTC_HOST_TARGET_IMG_REF", "docker.io/chaserhkj/arch-bootc-host")

default: prepare-all-persistent

prepare-all-images:
    for host in $(ls hosts); do just prepare-image $host; done;

prepare-all-persistent:
    for host in $(ls hosts); do [ -f "hosts/$host/LIVE" ] && continue; just prepare-image $host; done;

prepare-all-live:
    for host in $(ls hosts); do [ -f "hosts/$host/LIVE" ] || continue; just prepare-image $host; done;

prepare-image host:
    just configure-image host
    just tag-image host
    just push-image host

configure-image host:
    #!/usr/bin/env bash
    host_dir="hosts/{{host}}"
    [ -f $host_dir/BASE ] && read -r base_img < "$host_dir/BASE"
    [ -z $CREDS ] && export CREDS="$(gpg --decrypt creds.gpg)"$'\n'

    CTR_BUILD_FROM=$base_img \
        ${buildImageScript} \
        --secret=id=creds,env=CREDS \
        --iidfile {{host}}.intermediate.id \
        -f Containerfile "$host_dir"

    if [ -f $host_dir/Containerfile ]; then
        read -r intermediate_img < {{host}}.intermediate.id
        CTR_BUILD_CONTEXT_FROM_BASE=base CTR_BUILD_CONTEXT_IMG_BASE=$intermediate_img \
            ${buildImageScript} \
            --iidfile {{host}}.pre-live.id \
            -f "$host_dir/Containerfile" "$host_dir"
    else
        cp {{host}}.intermediate.id {{host}}.pre-live.id
    fi

    read -r pre_live_image < {{host}}.pre-live.id
    if [ -f $host_dir/LIVE ]; then
        CTR_BUILD_CONTEXT_FROM_BASE=base CTR_BUILD_CONTEXT_IMG_BASE=$pre_live_image \
            ${buildImageScript} \
            --iidfile {{host}}.final.id \
            -f Containerfile.live "$host_dir"
        read -r final_image < {{host}}.final.id
    else
        final_image=$pre_live_image
    fi

    ${CTR_BUILD_TOOL} tag $final_image localhost/bootc-arch-host:{{host}}

tag-image host:
    ${CTR_BUILD_TOOL} tag localhost/bootc-arch-host:{{host}} ${CTR_ARCH_BOOTC_HOST_TARGET_IMG_REF}:{{host}}

push-image host:
    [ -f hosts/{{host}}/LIVE ] && push_flags="--compression-format=gzip --force-compression" || push_flags=  ; \
    retry=0; max_retry=${CTR_PUSH_RETRIES:-3}; backoff=${CTR_PUSH_RETRY_BACKOFF:-"1s"}; \
    until [ "$retry" -ge $max_retry ]; do \
    ${CTR_BUILD_TOOL} push $push_flags ${CTR_PUSH_FLAGS:-} ${CTR_ARCH_BOOTC_HOST_TARGET_IMG_REF}:{{host}} && break; \
    retry=$((retry+1)); sleep "$backoff"; done

