set dotenv-load := true
CTR_ARCH_BOOTC_HOST_TARGET_IMG_REF := env("CTR_ARCH_BOOTC_HOST_TARGET_IMG_REF", "docker.io/chaserhkj/arch-bootc-host")

default: prepare-all-persistent

prepare-all-images:
    for host in $(ls hosts); do just prepare-image $host; done;

prepare-all-persistent:
    for host in $(ls hosts); do [ -f "hosts/$host/LIVE" ] && continue; just prepare-image $host; done;

prepare-all-live:
    for host in $(ls hosts); do [ -f "hosts/$host/LIVE" ] || continue; just prepare-image $host; done;

prepare-image host: (configure-image host)
    ${CTR_BUILD_TOOL} tag localhost/bootc-arch-host:{{host}} ${CTR_ARCH_BOOTC_HOST_TARGET_IMG_REF}:{{host}}
    [ -f hosts/{{host}}/LIVE ] && push_flags="--compression-format=gzip --force-compression" || push_flags=  ; \
    ${CTR_BUILD_TOOL} push $push_flags ${CTR_ARCH_BOOTC_HOST_TARGET_IMG_REF}:{{host}}

configure-image host:
    #!/usr/bin/env bash
    host_dir="hosts/{{host}}"
    [ -f $host_dir/BASE ] && read -r base_img < "$host_dir/BASE"
    [ -n $base_img ] && base_flag="--from=$base_img"
    export CREDS="$(gpg --decrypt creds.gpg)" || exit 1

    ${CTR_BUILD_TOOL} build --secret=id=creds,env=CREDS --iidfile {{host}}.intermediate.id -f Containerfile "$base_flag" "$host_dir" ${CTR_BUILD_FLAGS}

    if [ -f $host_dir/Containerfile ]; then
        read -r intermediate_img < {{host}}.intermediate.id
        ${CTR_BUILD_TOOL} build --iidfile {{host}}.pre-live.id --build-arg BASE=$intermediate_img "$host_dir" ${CTR_BUILD_FLAGS}
    else
        cp {{host}}.intermediate.id {{host}}.pre-live.id
    fi

    read -r pre_live_image < {{host}}.pre-live.id
    if [ -f $host_dir/LIVE ]; then
        ${CTR_BUILD_TOOL} build --iidfile {{host}}.final.id -f Containerfile.live --build-arg BASE=$pre_live_image "$host_dir" ${CTR_BUILD_FLAGS}
        read -r final_image < {{host}}.final.id
    else
        final_image=$pre_live_image
    fi

    ${CTR_BUILD_TOOL} tag $final_image localhost/bootc-arch-host:{{host}}

