ARG PYTHON_VERSION=3.12
FROM ghcr.io/astral-sh/uv:python${PYTHON_VERSION}-trixie
ARG TORCH_PLATFORM=rocm7.1
ARG TORCH_VERSION=2.9.1

RUN --mount=type=cache,target=/root/.cache/uv,id=uv \
    uv pip install --system torch==${TORCH_VERSION} torchvision torchaudio --index-url=https://download.pytorch.org/whl/${TORCH_PLATFORM}

ENTRYPOINT ["/usr/local/bin/python3"]