mod arch-config 'arch-host-config/'

CTR_ARCH_BOOTC_BASE := env("CTR_ARCH_BOOTC_BASE", "")

export CTR_BUILD_CONTEXT_FROM_BOOTC_ARCH_BASE := "bootc/arch"
export CTR_BUILD_CONTEXT_IMG_BOOTC_ARCH_BASE := env(
    "CTR_BASE_ARCH_BOOTC",
    "ghcr.io/bootcrew/arch-bootc:latest"
    )

default:
    just build-image arch-k0s
    just build-image arch-k0s-config
    just build-image arch-common-config
    just build-image arch-common-home-config
    just build-variant-image arch-common-config arch-k0s-config
    just build-variant-image arch-common-home-config arch-k0s-config
    just build-variant-image arch-amd arch-common-home-config-k0s-config

build-all:
    just build-base-images
    just default

build-base-images:
    just build-image arch-base ${CTR_ARCH_BOOTC_BASE}
    just build-live-images arch ${CTR_ARCH_BOOTC_BASE}

build-live-images distro:
    ${buildImageScript} {{distro}}-live --target builder -t bootc-{{distro}}-live-builder
    ${buildImageScript} {{distro}}-live -t bootc-{{distro}}-live

build-image subdir:
    ${buildImageScript} {{subdir}} -t bootc-{{subdir}}

build-variant-image subdir base:
    #!/usr/bin/env bash
    set -e
    postfix=$(echo "{{base}}" | sed "s/[^-]*-//")
    manifest={{subdir}}/Containerfile
    # Resolve base image
    base_arg=$(grep "ARG BASE=.*$" $manifest| head -n1)
    if [[ -n "$base_arg" ]]; then
        orig_base_image=$(echo $base_arg | sed "s/^ARG BASE=//")
    else
        orig_base_image=$(grep "^FROM" $manifest|tail -n1|choose 1)
    fi
    [[ $orig_base_image == *-base ]] && base_image=bootc-{{base}} || base_image=$orig_base_image-$postfix
    echo "Use base $base_image for bootc-{{subdir}}-$postfix"
    ${CTR_BUILD_TOOL} build {{subdir}} -t bootc-{{subdir}}-$postfix --build-arg BASE=$base_image ${CTR_BUILD_FLAGS} 