mod arch-config 'arch-host-config/'

export CTR_BUILD_CONTEXT_FROM_BOOTC_ARCH_BASE := "bootc-arch"
export CTR_BUILD_CONTEXT_IMG_BOOTC_ARCH_BASE := env(
    "CTR_BASE_ARCH_BOOTC",
    "ghcr.io/bootcrew/arch-bootc:latest"
    )

arch_aur_builder_img := env("CTR_ARCH_AUR_BUILDER_IMG", "")
export CTR_BUILD_CONTEXT_FROM_ARCH_AUR_BUILDER := if arch_aur_builder_img != "" { "arch-aur-builder" } else {""}
export CTR_BUILD_CONTEXT_IMG_ARCH_AUR_BUILDER := arch_aur_builder_img

pkg_overrides_img := env("CTR_PKG_OVERRIDES_IMG", "")
export CTR_BUILD_CONTEXT_FROM_PKG_OVERRIDES := if pkg_overrides_img != "" { "pkg-overrides" } else {""}
export CTR_BUILD_CONTEXT_IMG_PKG_OVERRIDES := pkg_overrides_img

builder_pkg_overrides_img := env("CTR_BUILDER_PKG_OVERRIDES_IMG", "")
export CTR_BUILD_CONTEXT_FROM_BUILDER_PKG_OVERRIDES := if builder_pkg_overrides_img != "" { "builder-pkg-overrides" } else {""}
export CTR_BUILD_CONTEXT_IMG_BUILDER_PKG_OVERRIDES := builder_pkg_overrides_img

default:
    just build-image arch-k0s
    just build-image arch-k0s-config
    just build-image arch-common-config
    just build-image arch-common-home-config
    just build-variant-image arch-common-config arch-k0s-config
    just build-variant-image arch-common-home-config arch-k0s-config-common-config
    just build-variant-image arch-amd arch-k0s-config-common-config-common-home-config

build-all:
    just build-base-images
    just default

build-base-images:
    just build-image arch-base
    just build-live-images arch

build-live-images distro:
    ${buildImageScript} --target builder -t bootc-{{distro}}-live-builder {{distro}}-live 
    ${buildImageScript} -t bootc-{{distro}}-live {{distro}}-live 

build-image subdir:
    ${buildImageScript} -t bootc-{{subdir}} {{subdir}}

build-variant-image subdir new_base:
    #!/usr/bin/env bash
    set -e
    postfix=$(echo "{{subdir}}" | sed "s/[^-]*-//")

    echo "Use base {{new_base}} for bootc-{{new_base}}-$postfix"

    export CTR_BUILD_CONTEXT_FROM_VARIANT_BASE=base
    export CTR_BUILD_CONTEXT_IMG_VARIANT_BASE=bootc-{{new_base}}

    ${buildImageScript} -t bootc-{{new_base}}-$postfix {{subdir}}