# Image that contains common configurations that are shared between hosts
ARG NIXPKGS_VERSION=nixos-25.11

FROM ghcr.io/nix-community/docker-nixpkgs/nix-flakes:${NIXPKGS_VERSION}-x86_64-linux as nix-static

ARG NIX_STATIC_REV=nixpkgs

RUN nix build ${NIX_STATIC_REV}#nixStatic

RUN cp /result/bin/nix /nixStatic

FROM scratch as builder-pkg-overrides

FROM arch-aur-builder as pkg-builder

# pkg overrides, used for toolchains
RUN --mount=type=bind,from=builder-pkg-overrides,target=/tmp/pkgs sudo bash <<'EOF'
[[ -z "$(ls -A /tmp/pkgs)" ]] && exit 0
pacman -U --noconfirm --needed /tmp/pkgs/*.pkg.tar.*
EOF

FROM pkg-builder as aur-builder

RUN aur sync -n --noview sesh-bin networkd-broker

FROM archlinux as blesh

ADD https://github.com/akinomyoga/ble.sh/releases/download/nightly/ble-nightly.tar.xz /

RUN tar -C / -xvf /ble-nightly.tar.xz

FROM bootc-arch-base as base
FROM base

RUN --mount=type=bind,from=nix-static,target=/var/mnt \
    install -m0755 /var/mnt/nixStatic /usr/bin

# wheel for sudo, kvm for krun
RUN useradd -M -G wheel,kvm hkj

# zram generator, to use zram as swap and save memory
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Sy --needed --noconfirm zram-generator

# Install BLE (Bash Line Editor) framework, and patch off C-r shortcuts
RUN --mount=type=bind,from=blesh,target=/tmp \
    bash /tmp/ble-nightly/ble.sh --install /usr/share && \
    sed "/ble-bind .* C-r.*/d" /usr/share/blesh/contrib/fzf-key-bindings.bash > /usr/share/blesh/fzf-key-bindings.bash

# Install CLI power tools
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Sy --needed --noconfirm tmux zoxide atuin fzf

RUN --mount=type=bind,from=aur-builder,source=/var/build/repo,target=/var/local-repo \
    --mount=type=tmpfs,target=/usr/lib/sysimage/lib/pacman/sync \
    --mount=type=tmpfs,target=/usr/lib/sysimage/cache/pacman/pkg \
    pacman -Sy --config /etc/pacman-local-repo.conf --needed --noconfirm sesh-bin networkd-broker

# Post installation steps for sesh
RUN mkdir -p /etc/bash_completion.d && echo "$(sesh completion bash)" > /etc/bash_completion.d/sesh.bash

# For mounting storage over network
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Sy --needed --noconfirm nfs-utils nvme-cli

COPY rootfs /

# Post-fs update hooks go here
RUN update-ca-trust
