FROM scratch as pkg-overrides
FROM scratch as builder-pkg-overrides

FROM arch-aur-builder as pkg-builder

# pkg overrides, used for toolchains
RUN --mount=type=bind,from=builder-pkg-overrides,target=/tmp/pkgs sudo bash <<'EOF'
[[ -z "$(ls -A /tmp/pkgs)" ]] && exit 0
pacman -U --noconfirm --needed /tmp/pkgs/*.pkg.tar.*
EOF

FROM pkg-builder as aur-pkgs

RUN aur sync -n --noview zerotier-systemd-manager-git

# Build ssh-key-dir to support $HOME/.ssh/authorized_keys.d
FROM pkg-builder as ssh-key-dir
USER root

RUN --mount=type=cache,target=/var/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/var/cache/pacman/pkg,id=pacman-cache \
    pacman -Sy --noconfirm rust git make

RUN git clone https://github.com/coreos/ssh-key-dir /work

WORKDIR /work

RUN mkdir -p /target && make RELEASE=1 && make install DESTDIR=/target RELEASE=1

FROM scratch as bashrc.d

COPY bashrc.d.sh /

# Base arch image with extended package setups, to be used as base for site-specific images
FROM bootc-arch
ARG PACMAN_FULL_SYNC_FLAGS
# shell command used to query for packages that are to be reinstalled
ARG PACMAN_REINSTALL_QUERY="pacman -Qq"

# Remove all thinning options in pacman.conf, these are designed for service containers but we are not
# Note that /etc/machine-id needs to be added if this is done
# This WILL be handled if image is eventually consumed by distrobox/bootc
# and we don't need to do anything about it
RUN sed -i '/^NoExtract *=.*$/d' /etc/pacman.conf

RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    --mount=type=bind,from=pkg-overrides,target=/tmp/pkg-overrides \
    env PACMAN_REINSTALL_QUERY="${PACMAN_REINSTALL_QUERY}" \
        PACMAN_FULL_SYNC_FLAGS="${PACMAN_FULL_SYNC_FLAGS}" \
    bash -ex <<'EOF'

pacman-key --init
pacman -Sy
pacman -S archlinux-keyring --noconfirm

# Reinstall everything to obtain the thinned files of default packages
# This effectively updates everything as well so we update keyring alongside
( eval ${PACMAN_REINSTALL_QUERY} ) | pacman -S --noconfirm -
pacman -Syyu ${PACMAN_FULL_SYNC_FLAGS} --noconfirm

# Install package overrides, mainly for kernel and kernel modules
[[ -z "$(ls -A /tmp/pkg-overrides)" ]] || pacman -U --noconfirm --needed /tmp/pkg-overrides/*.pkg.tar.*

# cleanup kernel files installed at default location
rm -rf /boot
mkdir -p /boot

# Explicitly use gpt-auto root on kernel cmdline
mkdir -p /usr/lib/bootc/kargs.d
echo 'kargs = [ "root=gpt-auto" ]' > /usr/lib/bootc/kargs.d/10-gpt-auto.toml

# After this, filesystem package overrides some bootc symlinks when reinstalling
# So we want to reinstate them
rm -rf /home /root /usr/local /srv /mnt /opt
mkdir -p /var/home /var/roothome /var/usrlocal /var/srv /var/opt /var/mnt
ln -sT var/home /home
ln -sT var/roothome /root
ln -sT ../var/usrlocal /usr/local
ln -sT var/srv /srv
ln -sT var/opt /opt
ln -sT var/mnt /mnt 
EOF

# Packages that need presence in initramfs thus must be installed before dracut run
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Sy --needed --noconfirm lvm2

RUN bash -ex <<'EOF'
# Check and clean up stale kernel module directories
num_kernels=0
for d in /usr/lib/modules/*; do
    pacman -Qo $d 1>&/dev/null && num_kernels=$((num_kernels + 1)) && continue
    rm -rf $d
done
[[ "$num_kernels" == "1" ]] || exit 1

# Always regenerate initramfs to include lvm
kver=$(ls /usr/lib/modules|sort|tail -n1)
dracut --verbose --force /usr/lib/modules/$kver/initramfs.img
EOF

# locale-gen
RUN sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen

# archlinuxcn repo configurations
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    printf '[archlinuxcn]\nServer = https://repo.archlinuxcn.org/$arch\n' | tee -a /etc/pacman.conf && \
    pacman -Sy --noconfirm --needed archlinuxcn-keyring

# Local repo configurations
RUN cp -f /etc/pacman.conf /etc/pacman-local-repo.conf && \ 
    printf '[sitepkgs]\nSigLevel = Never\nServer = file:///var/local-repo/\n' | tee -a /etc/pacman-local-repo.conf

# Common tools, including tools that might be needed to work with bootc
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Sy --needed --noconfirm sudo neovim bash-completion moreutils inetutils man less jq yq bubblewrap fsverity-utils ripgrep fd sd lsd bat bottom dust duf dog && \
    ln -sT nvim /usr/bin/vim

# Container tools
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Sy --needed --noconfirm podman buildah skopeo umoci docker-compose podman-docker distrobox flatpak fuse-overlayfs krun podlet

# AUR packages
RUN --mount=type=bind,from=aur-pkgs,source=/var/build/repo,target=/var/local-repo \
    --mount=type=tmpfs,target=/usr/lib/sysimage/lib/pacman/sync \
    --mount=type=tmpfs,target=/usr/lib/sysimage/cache/pacman/pkg \
    pacman -Sy --config /etc/pacman-local-repo.conf --needed --noconfirm zerotier-systemd-manager-git

# Base firewall and networking setup
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Sy --needed --noconfirm ufw openssh zerotier-one wireguard-tools

# Install bashrc.d setup
RUN --mount=type=bind,from=bashrc.d,target=/tmp \
    cat /tmp/bashrc.d.sh >> /etc/bash.bashrc && \
    mkdir -p /etc/bashrc.d

# Bootc completion
RUN bootc completion bash > /etc/bashrc.d/10-bootc-completion.sh

# Install ssh-key-dir
COPY --from=ssh-key-dir /target /

# Copy rootfs that has all file-based configurations

COPY rootfs /
