FROM ghcr.io/open-webui/open-terminal:slim AS base

FROM scratch as nix-install
ARG NIX_INSTALLER_VER=2.34.1
ADD --chmod=755 https://github.com/NixOS/nix-installer/releases/download/${NIX_INSTALLER_VER}/nix-installer-x86_64-linux /nix-installer

FROM base AS final
RUN --mount=type=bind,from=nix-install,target=/mnt /mnt/nix-installer \
    install linux --no-confirm --init none --nix-build-user-count 0 --no-start-daemon \
        --extra-conf "sandbox = false" --extra-conf "build-users-group =" && \
    chown user:user -R /nix

ENV PATH="/nix/var/nix/profiles/default/bin:/home/user/.nix-profile/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

RUN su user -c "nix profile add nixpkgs#uv nixpkgs#bun nixpkgs#go nixpks#cargo"

RUN su user -c "nix profile add nixpkgs#curl nixpkgs#defuddle"

RUN su user -c "nix profile add nixpkgs#mcporter nixpkgs#ctx7"

COPY <<'EOF' /entrypoint-wrapper.sh
#!/bin/bash
. /nix/var/nix/profiles/default/etc/profile.d/nix.sh
exec /usr/bin/tini -- /app/entrypoint-slim.sh "$@"
EOF

RUN chmod +x /entrypoint-wrapper.sh

ENTRYPOINT ["/entrypoint-wrapper.sh"]
CMD ["run"]
