# From ../arch-base
ARG BASE=bootc-arch-base

FROM ${BASE}
ARG K0S_VERSION="v1.35.1+k0s.0"

ADD --chmod=0755 "https://github.com/k0sproject/k0s/releases/download/${K0S_VERSION}/k0s-${K0S_VERSION}-amd64" /usr/bin/k0s

# cri-o and cni need to use /opt as image directory
RUN [ -L /opt ] && { rm -f /opt && mkdir -p /opt;} || exit 0

# Alternative runtime
# cri-o uses iptables-nft, that replaces iptables, need to perform that replacement first
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    yes | pacman -Sy --needed iptables-nft && \
    pacman -S --noconfirm --needed crun krun cri-o

# /opt/cni needs to be writable, copy stock version from /usr/lib/cni to /var/lib/cni/bin and link it from /opt/cni
# The copy is also done by tmpfiles.d as well, for updates
RUN mkdir -p /var/lib/cni/bin && \
    cp -a /usr/lib/cni/. /var/lib/cni/bin/ && \
    rm -rf /opt/cni/bin && \
    ln -sfT /var/lib/cni/bin /opt/cni/bin

# Other host tools required by k0s
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -S --noconfirm --needed inetutils

COPY rootfs /