# From ../arch-base
ARG BASE=bootc-arch-base

FROM ${BASE}
ARG K0S_VERSION="v1.34.3+k0s.0"

ADD --chmod=0755 "https://github.com/k0sproject/k0s/releases/download/${K0S_VERSION}/k0s-${K0S_VERSION}-amd64" /usr/bin/k0s

# Alternative runtime
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -S --noconfirm --needed crun krun

# Other host tools required by k0s
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Sy --noconfirm --needed inetutils

COPY rootfs /