ARG BASE=nvidia/cuda:13.1.0-devel-ubuntu24.04
FROM ${BASE}

RUN --mount=type=cache,target=/var/cache/apt,id=apt \
    apt-get update && apt-get install -y git sox libsox-dev tini curl git-lfs

COPY --from=ghcr.io/astral-sh/uv:latest / /usr/bin/

RUN git clone --recursive https://github.com/FunAudioLLM/CosyVoice.git /work/cosyvoice

WORKDIR /work

RUN uv venv --python 3.10 /venv/cosyvoice && \
    uv venv --python 3.10 /venv/indextts && \
    uv venv --python 3.13 /venv/qwen-tts && \
    uv venv --python 3.10 /venv/lab

RUN cd /work/cosyvoice && VIRTUAL_ENV=/venv/cosyvoice \
    uv pip install -r requirements.txt --index-strategy unsafe-best-match

RUN cd /work/cosyvoice && uvx --from=huggingface_hub hf download \
    --local-dir pretrained_models/Fun-CosyVoice3-0.5B \
    FunAudioLLM/Fun-CosyVoice3-0.5B-2512

RUN VIRTUAL_ENV=/venv/cosyvoice \
    uv pip install --upgrade PyYAML hyperpyyaml

RUN --mount=type=cache,target=/var/cache/apt,id=apt \
    apt-get install -y unzip
    
RUN cd /work && curl -Lo main.zip https://github.com/index-tts/index-tts/archive/refs/heads/main.zip && \
    unzip main.zip && mv index-tts-main index-tts && rm main.zip

RUN cd /work/index-tts && VIRTUAL_ENV=/venv/indextts \
    uv sync --all-extras --active

RUN cd /work/index-tts && uvx --from=huggingface_hub hf download \
    --local-dir checkpoints IndexTeam/IndexTTS-2

RUN VIRTUAL_ENV=/venv/qwen-tts \
    uv pip install qwen-tts && \
    uv pip install flash-attn --no-build-isolation

RUN uvx --from=huggingface_hub hf download \
    Qwen/Qwen3-TTS-12Hz-1.7B-CustomVoice
RUN uvx --from=huggingface_hub hf download \
    Qwen/Qwen3-TTS-12Hz-1.7B-VoiceDesign
RUN uvx --from=huggingface_hub hf download \
    Qwen/Qwen3-TTS-12Hz-1.7B-Base

RUN --mount=type=cache,target=/var/cache/apt,id=apt \
    apt-get install -y ffmpeg

RUN VIRTUAL_ENV=/venv/lab uv pip install jupyter jupyter-collaboration && \
    VIRTUAL_ENV=/venv/cosyvoice uv pip install ipykernel jupyter && \
    VIRTUAL_ENV=/venv/cosyvoice uv run python3 -m ipykernel install \
        --name "cosyvoice" --display-name "Python (Cosyvoice)" && \
    VIRTUAL_ENV=/venv/indextts uv pip install ipykernel jupyter && \
    VIRTUAL_ENV=/venv/indextts uv run python3 -m ipykernel install \
        --name "indextts" --display-name "Python (IndexTTS)"

VOLUME /work/persistent

ENTRYPOINT ["tini", "--"]

CMD ["env", "VIRTUAL_ENV=/venv/lab", "uv", "run", "jupyter", "lab", \
    "--no-browser", "-y", "--allow-root", \
    "--port=50000", "--ip=0.0.0.0", \
    "--LabApp.token=", "--LabApp.password="]

EXPOSE 50000