FROM docker.io/library/caddy:2-builder AS builder

RUN xcaddy build \
    --with github.com/aksdb/caddy-cgi/v2

FROM docker.io/library/caddy:2

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

RUN apk add --no-cache git git-daemon

RUN mkdir -p /var/lib/git/health/ready && cd /var/lib/git/health/ready && \
    git init --bare

COPY Caddyfile /etc/caddy/Caddyfile