# Use ubuntu 24.04 as base image
# Since this is what used by llama.cpp
ARG BASE=docker.io/library/ubuntu:24.04

FROM docker.io/archlinux/archlinux as extractor
ARG THE_ROCK_VERSION=7.12.0a20260202
ARG THE_ROCK_VARIANT=gfx1151

RUN --mount=type=cache,target=/var/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/var/cache/pacman/pkg,id=pacman-cache \
    pacman -Sy wget --needed --noconfirm

RUN wget https://therock-nightly-tarball.s3.amazonaws.com/therock-dist-linux-${THE_ROCK_VARIANT}-${THE_ROCK_VERSION}.tar.gz -O /dist.tar.gz

RUN mkdir -p /opt/rocm && tar -C /opt/rocm -xf /dist.tar.gz

FROM ${BASE} as therock-base

COPY --from=extractor /opt/rocm/ /opt/rocm/

ENV PATH="${PATH}:/opt/rocm/bin" LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/opt/rocm/lib:/opt/rocm/lib/llvm/lib" HIP_PLATFORM=amd

RUN --mount=type=bind,target=/run/mnt bash /run/mnt/deps.sh

FROM ghcr.io/nix-community/docker-nixpkgs/nix-flakes:latest-x86_64-linux as migraphx-nix-provider

RUN mkdir -p /nix-profile && nix profile add --profile /nix-profile/default \
    nixpkgs#git nixpkgs#cacert nixpkgs#cmake

FROM therock-base as migraphx

COPY --from=ghcr.io/astral-sh/uv:latest / /usr/bin/
COPY --from=migraphx-nix-provider /nix /nix
COPY --from=migraphx-nix-provider /nix-profile /usr/nix-profile

ENV PATH=/usr/nix-profile/default/bin:$PATH \
    LD_LIBRARY_PATH=/usr/nix-profile/default/lib:$LD_LIBRARY_PATH \
    SSL_CERT_FILE=/usr/nix-profile/default/etc/ssl/certs/ca-bundle.crt

RUN uv venv --python 3.12 /usr/python-env

ENV PATH=/usr/python-env/bin:$PATH VIRTUAL_ENV=/usr/python-env

RUN uv pip install cget git+https://github.com/ROCm/rbuild

RUN git clone https://github.com/ROCm/AMDMIGraphX /work

WORKDIR /work

FROM therock-base