# Combined image for therock-llama-cpp and therock-sd-cpp
FROM therock-sd-cpp as sd
FROM docker.io/library/ubuntu:24.04 as patcher

RUN --mount=type=cache,target=/var/cache/apt,id=apt \
    apt-get update && apt-get install -y patchelf

COPY --from=sd /sd.cpp /sd.cpp

RUN patchelf --set-rpath /llama.cpp /sd.cpp/sd-cli && \
    patchelf --set-rpath /llama.cpp /sd.cpp/sd-server

FROM therock-llama-cpp

COPY --from=patcher /sd.cpp /sd.cpp