# Use base image with SDKs specific to accelerator hardware
ARG BASE=localhost/therock-rocm
# Install extra tools by nix
FROM ghcr.io/nix-community/docker-nixpkgs/nix-flakes:latest-x86_64-linux as nix-provider

RUN mkdir -p /nix-profile && nix profile add --profile /nix-profile/default \
    nixpkgs#git \
    nixpkgs#cacert \
    nixpkgs#libxcb

FROM ${BASE}
ARG JUPYTER_PY_VERSION=3.14
ARG RUNTIME_TYPE=rocm

COPY --from=ghcr.io/astral-sh/uv:latest / /usr/bin/
COPY --from=docker.io/stagex/tini /usr/sbin/tini-static /usr/bin/tini
COPY --from=nix-provider /nix /nix
COPY --from=nix-provider /nix-profile /usr/nix-profile

ENV PATH=/usr/nix-profile/default/bin:$PATH \
    LD_LIBRARY_PATH=/usr/nix-profile/default/lib:$LD_LIBRARY_PATH \
    SSL_CERT_FILE=/usr/nix-profile/default/etc/ssl/certs/ca-bundle.crt

# Working directory for storing persistent work data including venvs
WORKDIR /work
VOLUME /work

# Persistent jupyter kernel definitions
VOLUME /usr/local/share/jupyter/kernels

RUN uv venv --python ${JUPYTER_PY_VERSION} /jupyter && \
    VIRTUAL_ENV=/jupyter uv pip install jupyter jupyterlab-katex \
    jupyter-server-proxy jupyterlab-git jupyterlab-lsp \
    lckr_jupyterlab_variableinspector sidecar jupyterlab_iframe \
    jupyterlab-code-formatter black isort jupyter-collaboration 

# For workload virtual environments
# Ensure uv cache is in the same fs, this makes them hard linked instead of copied
ENV UV_CACHE_DIR=/work/uv-cache HF_HOME=/work/hf-home

# For use within notebooks
ENV DATA_ROOT=/work RUNTIME_TYPE=${RUNTIME_TYPE}

ENTRYPOINT ["tini", "--"]

CMD ["env", "VIRTUAL_ENV=/jupyter", "uv", "run", "jupyter", "lab", \
    "--no-browser", "-y", "--allow-root", \
    "--port=5050", "--ip=0.0.0.0", \
    "--ServerApp.token=", "--ServerApp.password=", "--ServerApp.allow_origin=*" ]

EXPOSE 5050
