experimental-features = nix-command flakes ca-derivations
keep-outputs = true
build-users-group = nixbld
sandbox = true
substituters = https://ncps.0.zt/ https://cache.nixos.org 
trusted-public-keys = ncps.ncps.svc-0:pBmT+khbLR5AV/xPV5MCXVW82YowK7Lw6tO/dFT8eGI= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= 
post-build-hook = /etc/nix/upload-to-ncps.sh