ARG BASE=ghcr.io/chaserhkj/containers/therock-rocm-gfx1151

FROM scratch as nix-install
ADD https://artifacts.nixos.org/nix-installer /nix-installer

FROM ${BASE}
ARG THE_ROCK_VARIANT=gfx1151

RUN --mount=type=bind,from=nix-install,target=/mnt /bin/sh /mnt/nix-installer \
    install linux --no-confirm --init none --extra-conf "sandbox = false"

RUN export USER=root HOME=/root && . /nix/var/nix/profiles/default/etc/profile.d/nix.sh && \
    nix profile add nixpkgs#git nixpkgs#uv nixpkgs#tini && nix store gc

RUN git clone https://github.com/fishaudio/fish-speech /work

WORKDIR /work

RUN uv venv -p 3.12 && . .venv/bin/activate && \
    uv sync --no-install-package torch --no-install-package torchaudio && \
    uv pip install -i https://rocm.nightlies.amd.com/v2/${THE_ROCK_VARIANT} && \
        torch ~=2.8.0