ARG BASE=ghcr.io/chaserhkj/containers/therock-rocm-gfx1151

FROM scratch as nix-install
ADD --chmod=755 https://github.com/NixOS/nix-installer/releases/download/2.34.1/nix-installer-x86_64-linux /nix-installer

FROM ${BASE}
ARG THE_ROCK_VARIANT=gfx1151

RUN --mount=type=bind,from=nix-install,target=/mnt /mnt/nix-installer \
    install linux --no-confirm --init none --extra-conf "sandbox = false"

RUN export USER=root HOME=/root && . /nix/var/nix/profiles/default/etc/profile.d/nix.sh && \
    nix profile add nixpkgs#git nixpkgs#uv nixpkgs#tini && nix store gc

RUN export USER=root HOME=/root && . /nix/var/nix/profiles/default/etc/profile.d/nix.sh && \
    git clone https://github.com/fishaudio/fish-speech /work

WORKDIR /work

RUN export USER=root HOME=/root && . /nix/var/nix/profiles/default/etc/profile.d/nix.sh && \
    uv venv -p 3.12 && . .venv/bin/activate && \
    uv sync --no-install-package torch --no-install-package torchaudio && \
    uv pip install -i https://rocm.nightlies.amd.com/v2/${THE_ROCK_VARIANT} && \
        torch ~=2.8.0