FROM docker.io/library/ubuntu:24.04 as base
FROM docker.io/archlinux/archlinux as extractor
ARG GPU_ARCH=gfx1151

RUN --mount=type=cache,target=/var/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/var/cache/pacman/pkg,id=pacman-cache \
    pacman -Sy unzip jq wget binutils --needed --noconfirm

ENV GPU_ARCH=${GPU_ARCH}

RUN bash -ex <<'EOF'
build=$(curl https://api.github.com/repos/lemonade-sdk/llamacpp-rocm/releases/latest -s | jq .name -r)
wget -nv -O /release.zip https://github.com/lemonade-sdk/llamacpp-rocm/releases/download/${build}/llama-${build}-ubuntu-rocm-${GPU_ARCH}-x64.zip
mkdir -p /target
cd /target
unzip /release.zip
for f in /target/*; do
[[ -f $f ]] || continue
readelf -h $f | grep "Executable file" 2>&1 1>&/dev/null || continue
chmod +x $f
done
EOF

FROM base

RUN --mount=type=cache,target=/var/cache/apt,id=apt \
    apt-get update -y && apt-get install -y libatomic1 curl

COPY --from=extractor /target /llama.cpp

ENV PATH="/llama.cpp:${PATH}"

ENTRYPOINT [ "llama-server" ]