default:
    just build arch
    just build arch-common-gui
    just build arch-generic
    just build arch-steam

build variant:
    ${CTR_BUILD_TOOL} build {{variant}} -t distrobox-{{variant}} ${CTR_BUILD_FLAGS}