ARG BASE=nvidia/cuda:13.1.0-devel-ubuntu24.04
FROM ${BASE}

RUN --mount=type=cache,target=/var/cache/apt,id=apt \
    apt-get update && apt-get install -y git sox libsox-dev tini curl

COPY --from=ghcr.io/astral-sh/uv:latest / /usr/bin/

RUN git clone --recursive https://github.com/FunAudioLLM/CosyVoice.git /work

WORKDIR /work

RUN uv venv --python3.12 /venv

ENV VIRTUAL_ENV=/venv

RUN uv pip install -r requirements.txt --index-strategy unsafe-best-match

RUN uvx --from=huggingface_hub hf download \
    --local-dir pretrained_models/Fun-CosyVoice3-0.5B \
    FunAudioLLM/Fun-CosyVoice3-0.5B-2512

# For deepspeed
RUN uv pip install 'cuda-toolkit[all]==12.1.1'

ENV CUDA_HOME=/venv/lib/python3.10/site-packages/nvidia/cuda_nvcc

ENTRYPOINT ["tini", "--"]

CMD ["uv", "run", "python3", "webui.py", "--port", "50000", "--model_dir", "pretrained_models/Fun-CosyVoice3-0.5B"]

EXPOSE 50000