ARG BASE=nvidia/cuda:13.1.0-devel-ubuntu24.04
FROM ${BASE}

RUN --mount=type=cache,target=/var/cache/apt,id=apt \
    apt-get update && apt-get install -y git sox libsox-dev tini curl

COPY --from=ghcr.io/astral-sh/uv:latest / /usr/bin/

RUN git clone --recursive https://github.com/FunAudioLLM/CosyVoice.git /work

WORKDIR /work

RUN uv venv --python 3.10 /venv

ENV VIRTUAL_ENV=/venv

RUN uv pip install -r requirements.txt --index-strategy unsafe-best-match

RUN uvx --from=huggingface_hub hf download \
    --local-dir pretrained_models/Fun-CosyVoice3-0.5B \
    FunAudioLLM/Fun-CosyVoice3-0.5B-2512

RUN uv pip install --upgrade PyYAML hyperpyyaml

RUN --mount=type=cache,target=/var/cache/apt,id=apt \
    apt-get install -y ffmpeg

RUN uv pip install jupyter 

RUN uv pip install -e .

VOLUME /work/persistent

ENTRYPOINT ["tini", "--"]

CMD ["uv", "run", "jupyter", "notebook",
    "--no-browser", "-y", "--allow-root",
    "--ServerApp.port=50000", "--ServerApp.ip=0.0.0.0"]

EXPOSE 50000