FROM scratch as pkg-overrides
FROM scratch as builder-pkg-overrides

FROM arch-aur-builder as pkg-builder

# pkg overrides, used for toolchains
RUN --mount=type=bind,from=builder-pkg-overrides,target=/tmp sudo bash <<'EOF'
[[ -z "$(ls -A /tmp)" ]] && exit 0
pacman -U --noconfirm --needed /tmp/*.pkg.tar.*
EOF

# From ../arch-base
FROM bootc-arch-base as builder

RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Sy git kexec-tools erofs-utils --needed --noconfirm

FROM builder as initramfs-build

RUN git clone https://github.com/chaserhkj/bootc-live /work
WORKDIR /work

RUN for mod in /work/modules.d/* ; do ln -s $mod /usr/lib/dracut/modules.d; done;
RUN /bin/sh for-container.sh build-initrd-all-mods

# Build forked cfsctl
FROM pkg-builder as cfsctl
USER root

RUN --mount=type=cache,target=/var/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/var/cache/pacman/pkg,id=pacman-cache \
    pacman -Sy --noconfirm rust git make

RUN git clone https://github.com/chaserhkj/composefs-rs /work

WORKDIR /work

RUN cargo build --release -p cfsctl && cp target/release/cfsctl /cfsctl


FROM bootc-arch
ARG PACMAN_FULL_SYNC_FLAGS

# pkg overrides, used for kernel and kernel modules (zfs, etc.)
RUN --mount=type=bind,from=pkg-overrides,target=/tmp bash <<'EOF'
[[ -z "$(ls -A /tmp)" ]] && exit 0
pacman -U --noconfirm --needed /tmp/*.pkg.tar.*
EOF

# archlinuxcn repo configurations
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    printf '[archlinuxcn]\nServer = https://repo.archlinuxcn.org/$arch\n' | tee -a /etc/pacman.conf && \
    pacman -Sy --noconfirm --needed archlinuxcn-keyring

RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Syyu ${PACMAN_FULL_SYNC_FLAGS} --noconfirm

RUN --mount=type=bind,from=initramfs-build,target=/tmp \
    cp -f /tmp/work/initrd-all-mods.img /usr/lib/modules/*/initramfs.img

# Common tools, including tools that might be needed to work with bootc
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Sy --needed --noconfirm sudo vim bash-completion man less jq bubblewrap fsverity-utils ripgrep fd sd lsd bat bottom

# Create a user "liveuser" without password, and configure sudo for it
RUN useradd -m liveuser && passwd -d liveuser && \
    echo 'liveuser ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/99_liveuser

# Wireless connection manager
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Sy --needed --noconfirm iwd

# Tools associated with installation tasks
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Sy --needed --noconfirm efibootmgr gptfdisk parted ddrescue

# Bootc completion
RUN bootc completion bash >> /etc/bash.bashrc

# Install cfsctl
COPY --from=cfsctl /cfsctl /usr/bin

# Install bootc-cfsctl-cleanup
ADD --chmod=0755 \
    https://gist.githubusercontent.com/chaserhkj/ad666a558800abeae9bc51202ad0da78/raw/7d45923cafb24bfa76fb57035cbb5d1fc8d4e72a/bootc-cfsctl-cleanup \
    /usr/bin/bootc-cfsctl-cleanup

# Layering other live-system-specific configurations
COPY rootfs /