FROM scratch as pkg-overrides
FROM scratch as builder-pkg-overrides

FROM arch-aur-builder as pkg-builder

# pkg overrides, used for toolchains
RUN --mount=type=bind,from=builder-pkg-overrides,target=/tmp/pkgs sudo bash <<'EOF'
[[ -z "$(ls -A /tmp/pkgs)" ]] && exit 0
pacman -U --noconfirm --needed /tmp/pkgs/*.pkg.tar.*
EOF

# From ../arch-base
FROM bootc-arch-base as builder

RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Sy git kexec-tools erofs-utils --needed --noconfirm

FROM builder as initramfs-build

RUN git clone https://github.com/chaserhkj/bootc-live /work
WORKDIR /work

RUN for mod in /work/modules.d/* ; do ln -s $mod /usr/lib/dracut/modules.d; done;
RUN /bin/sh for-container.sh build-initrd-all-mods

FROM bootc-arch
ARG PACMAN_FULL_SYNC_FLAGS

# archlinuxcn repo configurations
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    printf '[archlinuxcn]\nServer = https://repo.archlinuxcn.org/$arch\n' | tee -a /etc/pacman.conf && \
    pacman -Sy --noconfirm --needed archlinuxcn-keyring

RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Syyu ${PACMAN_FULL_SYNC_FLAGS} --noconfirm

RUN --mount=type=bind,from=pkg-overrides,target=/tmp/pkgs bash -ex <<'EOF'
# pkg overrides, used for kernel and kernel modules (zfs, etc.)
[[ -z "$(ls -A /tmp/pkgs)" ]] && exit 0
pacman -U --noconfirm --needed /tmp/pkgs/*.pkg.tar.*
# cleanup kernel files installed at default location
rm -rf /boot
mkdir -p /boot
EOF

# Check and clean up stale kernel module directories
RUN bash -ex <<'EOF'
num_kernels=0
for d in /usr/lib/modules/*; do
    pacman -Qo $d 1>&/dev/null && num_kernels=$((num_kernels + 1)) && continue
    rm -rf $d
done
[[ "$num_kernels" == "1" ]] && exit 0 || exit 1
EOF

RUN --mount=type=bind,from=initramfs-build,target=/tmp bash -ex <<'EOF'
kver=$(ls /usr/lib/modules|sort|tail -n1)
cp -f /tmp/work/initrd-all-mods.img /usr/lib/modules/$kver/initramfs.img
EOF

# Common tools, including tools that might be needed to work with bootc
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Sy --needed --noconfirm sudo vim bash-completion man less jq bubblewrap fsverity-utils ripgrep fd sd lsd bat bottom

# Create a user "liveuser" without password, and configure sudo for it
RUN useradd -m liveuser && passwd -d liveuser && \
    echo 'liveuser ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/99_liveuser

# Wireless connection manager
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Sy --needed --noconfirm iwd

# Tools associated with installation tasks
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Sy --needed --noconfirm efibootmgr gptfdisk parted ddrescue

# Bootc completion
RUN bootc completion bash >> /etc/bash.bashrc

# Layering other live-system-specific configurations
COPY rootfs /