# Overwrite-able bootc base, in case ghcr CI version is stale
ARG ZFS_VER_STRATEGY=latest
# From ../arch-base
FROM bootc-arch-base as builder

RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Sy git kexec-tools erofs-utils --needed --noconfirm

FROM builder as initramfs-build

RUN git clone https://github.com/chaserhkj/bootc-live /work
WORKDIR /work

RUN for mod in /work/modules.d/* ; do ln -s $mod /usr/lib/dracut/modules.d; done;
RUN /bin/sh for-container.sh build-initrd-all-mods

# Build forked cfsctl
FROM archlinux as cfsctl
# pacman flags attached to full sync commands
# use to pin packages
ARG PACMAN_FULL_SYNC_FLAGS=""

RUN --mount=type=cache,target=/var/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/var/cache/pacman/pkg,id=pacman-cache \
    pacman -Syyu ${PACMAN_FULL_SYNC_FLAGS} --noconfirm && \
    pacman -Sy --noconfirm rust git make

RUN git clone https://github.com/chaserhkj/composefs-rs /work

WORKDIR /work

RUN cargo build --release -p cfsctl && cp target/release/cfsctl /cfsctl


FROM bootc-arch as stage-pre-zfs

FROM stage-pre-zfs as stage-zfs-use-latest

# archzfs repo configurations
RUN printf '[archzfs]\nSigLevel = Required\nServer = https://github.com/archzfs/archzfs/releases/download/experimental\n' | tee -a /etc/pacman.conf && \
    pacman-key --init && pacman-key --recv-keys 3A9917BF0DED5C13F69AC68FABEC0A1208037BE9 && pacman-key --lsign-key 3A9917BF0DED5C13F69AC68FABEC0A1208037BE9

# archlinuxcn repo configurations
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    printf '[archlinuxcn]\nServer = https://repo.archlinuxcn.org/$arch\n' | tee -a /etc/pacman.conf && \
    pacman -Sy --noconfirm --needed archlinuxcn-keyring

FROM stage-pre-zfs as stage-zfs-use-pinned
ARG ZFS_PINNED_PKG_URL
ARG ZFS_PINNED_PKG_FILENAME

RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    curl -Lo /tmp/${ZFS_PINNED_PKG_FILENAME} ${ZFS_PINNED_PKG_URL} && \
    pacman --noconfirm -U /tmp/${ZFS_PINNED_PKG_FILENAME} && \
    rm /tmp/${ZFS_PINNED_PKG_FILENAME}

FROM stage-zfs-use-${ZFS_VER_STRATEGY}
ARG PACMAN_FULL_SYNC_FLAGS

RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Syyu ${PACMAN_FULL_SYNC_FLAGS} --noconfirm

RUN --mount=type=bind,from=initramfs-build,target=/tmp \
    cp -f /tmp/work/initrd-all-mods.img /usr/lib/modules/*/initramfs.img

# ZFS
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Sy --noconfirm --needed zfs-utils zfs-linux

# Common tools, including tools that might be needed to work with bootc
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Sy --needed --noconfirm sudo vim bash-completion man less jq bubblewrap fsverity-utils ripgrep fd sd lsd bat bottom

# Create a user "liveuser" without password, and configure sudo for it
RUN useradd -m liveuser && passwd -d liveuser && \
    echo 'liveuser ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/99_liveuser

# Wireless connection manager
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Sy --needed --noconfirm iwd

# Tools associated with installation tasks
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Sy --needed --noconfirm efibootmgr gptfdisk parted ddrescue

# Bootc completion
RUN bootc completion bash >> /etc/bash.bashrc

# Install cfsctl
COPY --from=cfsctl /cfsctl /usr/bin

# Install bootc-cfsctl-cleanup
ADD --chmod=0755 \
    https://gist.githubusercontent.com/chaserhkj/ad666a558800abeae9bc51202ad0da78/raw/7d45923cafb24bfa76fb57035cbb5d1fc8d4e72a/bootc-cfsctl-cleanup \
    /usr/bin/bootc-cfsctl-cleanup

# Layering other live-system-specific configurations
COPY rootfs /