# Use any debian/ubuntu based pytorch base image according to hardware
ARG BASE=rocm/pytorch:rocm7.1_ubuntu24.04_py3.13_pytorch_release_2.9.1

FROM ${BASE}

RUN --mount=type=cache,target=/var/cache/apt,id=apt \
    apt-get update && apt-get install -y vim bash-completion

RUN --mount=type=cache,target=/var/cache/apt,id=apt \
    apt-get update && apt-get install -y ssh

CMD "sshd"