name: repackage prebuilt binaries for rocm stack

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-rocm-prebuilt.yaml'
      - 'service/therock-llama-cpp/**'
      - 'service/therock-vllm/**'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 2,5'

permissions:
  contents: read
  packages: write

jobs:
  timestamp:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.set-ts.outputs.ts }}
    steps:
      - id: set-ts
        run: echo "ts=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

  build-llama-server-gfx1151:
    name: Build the llama server image for gfx1151 devices
    runs-on: ubuntu-latest
    needs: [timestamp]
    env:
      ADDITIONAL_TAG: ${{ needs.timestamp.outputs.timestamp }}
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push llama.cpp image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:service/therock-llama-cpp"
          push: true
          tags: |
            ghcr.io/chaserhkj/containers/llama-server-gfx1151:latest
            ghcr.io/chaserhkj/containers/llama-server-gfx1151:${{ env.ADDITIONAL_TAG }}
          file: Containerfile
          build-args: |
            GPU_ARCH=gfx1151

  build-llama-server-gfx103X:
    name: Build the llama server image for gfx103X devices
    runs-on: ubuntu-latest
    needs: [timestamp]
    env:
      ADDITIONAL_TAG: ${{ needs.timestamp.outputs.timestamp }}
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push llama.cpp image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:service/therock-llama-cpp"
          push: true
          tags: |
            ghcr.io/chaserhkj/containers/llama-server-gfx103x:latest
            ghcr.io/chaserhkj/containers/llama-server-gfx103x:${{ env.ADDITIONAL_TAG }}
          file: Containerfile
          build-args: |
            GPU_ARCH=gfx103X

  build-llama-server-gfx110X:
    name: Build the llama server image for gfx110X devices
    runs-on: ubuntu-latest
    needs: [timestamp]
    env:
      ADDITIONAL_TAG: ${{ needs.timestamp.outputs.timestamp }}
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push llama.cpp image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:service/therock-llama-cpp"
          push: true
          tags: |
            ghcr.io/chaserhkj/containers/llama-server-gfx110x:latest
            ghcr.io/chaserhkj/containers/llama-server-gfx110x:${{ env.ADDITIONAL_TAG }}
          file: Containerfile
          build-args: |
            GPU_ARCH=gfx110X

  build-vllm-gfx1151:
    name: Build the vllm image for gfx1151 devices
    runs-on: ubuntu-latest
    needs: [timestamp]
    env:
      ADDITIONAL_TAG: ${{ needs.timestamp.outputs.timestamp }}
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push vllm image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:service/therock-vllm"
          push: true
          tags: |
            ghcr.io/chaserhkj/containers/vllm-gfx1151:latest
            ghcr.io/chaserhkj/containers/vllm-gfx1151:${{ env.ADDITIONAL_TAG }}
          file: Containerfile
          build-args: |
            GPU_ARCH=gfx1151

  build-vllm-gfx110X:
    name: Build the vllm image for gfx110X devices
    runs-on: ubuntu-latest
    needs: [timestamp]
    env:
      ADDITIONAL_TAG: ${{ needs.timestamp.outputs.timestamp }}
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push vllm image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:service/therock-vllm"
          push: true
          tags: |
            ghcr.io/chaserhkj/containers/vllm-gfx110x:latest
            ghcr.io/chaserhkj/containers/vllm-gfx110x:${{ env.ADDITIONAL_TAG }}
          file: Containerfile
          build-args: |
            GPU_ARCH=gfx110X