name: repackage prebuilt binaries for rocm stack

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-rocm-prebuilt.yaml'
      - '.github/workflows/build-rocm-arch.yaml'
      - 'service/therock-llama-cpp/**'
      - 'service/therock-sd-cpp/**'
      - 'service/therock-vllm/**'
      - 'service/therock-ggml-engines/**'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 2,5'

permissions:
  contents: read
  packages: write

jobs:
  timestamp:
    runs-on: ubuntu-latest
    outputs:
      additional_tag: ${{ steps.set-ts.outputs.ts }}
    steps:
      - id: set-ts
        run: echo "ts=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

  build-gfx1151:
    name: Build ROCm images for gfx1151 devices
    needs: [timestamp]
    uses: ./.github/workflows/build-rocm-arch.yaml
    with:
      gpu_arch: gfx1151
      image_suffix: gfx1151
      additional_tag: ${{ needs.timestamp.outputs.additional_tag }}
      build_vllm: true
    secrets: inherit

  build-gfx103X:
    name: Build ROCm images for gfx103X devices
    needs: [timestamp]
    uses: ./.github/workflows/build-rocm-arch.yaml
    with:
      gpu_arch: gfx103X
      image_suffix: gfx103x
      additional_tag: ${{ needs.timestamp.outputs.additional_tag }}
      build_vllm: false
    secrets: inherit

  build-gfx110X:
    name: Build ROCm images for gfx110X devices
    needs: [timestamp]
    uses: ./.github/workflows/build-rocm-arch.yaml
    with:
      gpu_arch: gfx110X
      image_suffix: gfx110x
      additional_tag: ${{ needs.timestamp.outputs.additional_tag }}
      build_vllm: true
    secrets: inherit
