name: Build some service container images weekly

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-weekly.yaml'
      - 'builder/**'
      - 'service/git-server/**'
      - 'service/git-caddy/**'
      - 'service/cpu-ggml-engines/**'
      - 'service/democratic-csi.updated/**'
      - 'agent-sandbox/open-terminal/**'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 2,5'

permissions:
  contents: read
  packages: write

jobs:
  timestamp:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.set-ts.outputs.ts }}
    steps:
      - id: set-ts
        run: echo "ts=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

  build-builder:
    name: Build the builder image 
    needs: [timestamp]
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push the image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:builder/"
          file: Containerfile
          push: true
          tags: |
            ghcr.io/chaserhkj/containers/builder
            ghcr.io/chaserhkj/containers/builder:${{ needs.timestamp.outputs.timestamp }}

  build-git-server:
    name: Build the git-server service image 
    needs: [timestamp]
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push the image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:service/git-server"
          file: Containerfile
          push: true
          tags: |
            ghcr.io/chaserhkj/containers/git-server
            ghcr.io/chaserhkj/containers/git-server:${{ needs.timestamp.outputs.timestamp }}
  
  build-git-caddy:
    name: Build the git-caddy service image 
    needs: [timestamp]
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push the image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:service/git-caddy"
          file: Containerfile
          push: true
          tags: |
            ghcr.io/chaserhkj/containers/git-caddy
            ghcr.io/chaserhkj/containers/git-caddy:${{ needs.timestamp.outputs.timestamp }}

  build-democratic-csi:
    name: Build the democratic-csi service image with updated tools
    needs: [timestamp]
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push the image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:service/democratic-csi.updated"
          file: Containerfile
          push: true
          tags: |
            ghcr.io/chaserhkj/containers/democratic-csi.updated
            ghcr.io/chaserhkj/containers/democratic-csi.updated:${{ needs.timestamp.outputs.timestamp }}

  build-open-terminal:
    name: Build the open-terminal image
    needs: [timestamp]
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push the image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:agent-sandbox/open-terminal"
          file: Containerfile
          push: true
          tags: |
            ghcr.io/chaserhkj/containers/open-terminal
            ghcr.io/chaserhkj/containers/open-terminal:${{ needs.timestamp.outputs.timestamp }}

  build-cpu-ggml-engines:
    name: Build the cpu-ggml-engines image
    needs: [timestamp]
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push the image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:service/cpu-ggml-engines"
          file: Containerfile
          push: true
          tags: |
            ghcr.io/chaserhkj/containers/cpu-ggml-engines
            ghcr.io/chaserhkj/containers/cpu-ggml-engines:${{ needs.timestamp.outputs.timestamp }}
